### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by spikergit1** [jasperlee108/svndumpfilterIN#1]
Hi!  Thanks so much for the script.  It works great.  Windows operation suffers from the dreaded CR+LF mess.  I suggest you open files as binary to allow Windows clients to work properly and avoid readline() errors and later 'svadmin load' md5 hash errors.

**Comment by justinmassiot** [comment]
Tell me if I'm wrong but I think the last version of the code is now compatible with Windows-style line endings:
```python
    with open(input_dump, 'rb') as input_file:
        with open(output_dump, 'a+b') as output_file:
```
If true, this issue could be closed... ;-)

**Comment by freeamac** [comment]
I believe so but don't have a windows box at my disposal for confirmation. I will close in the meantime. If another issue, a new issue can be opened.

**Comment by beatcracker** [comment]
I'm using `svndumpfilterIN` exclusively on Windows and it works fine. I've processed ~10 Gb dump files without hitch.

**Comment by freeamac** [comment]
Awesome! Thanks for the confirmation.
