### ISSUE TITLE
Support for --targets option

### ISSUE THREAD

**Issue by craigblaster** [jasperlee108/svndumpfilterIN#11]
The official svndumpfilter supports the --targets option.
From http://svnbook.red-bean.com/en/1.8/svn.ref.svndumpfilter.html :
--targets FILENAME

```
Instructs svndumpfilter to read additional path prefixes—one per line—from the file located at FILENAME. This is especially useful for complex filtering operations which require more prefixes than the operating system allows to be specified on a single command line.
```

I needed to use this feature but it's not present in svndumpfilterIN, it would be a great addition.

**Comment by freeamac** [comment]
@craigblaster I know this is a late response to and ancient request, but doesn't the existing '-f', '--paths-file' option support your request?

**Comment by craigblaster** [comment]
@freeamac thanks for letting me know about that.
It looks like it might have worked but I struggle to remember and unfortunately not able to try it again.

**Comment by freeamac** [comment]
Thanks for the response. I will close out this issue. Of course if you come across the it again and the '-f' option does not suffice, it can be re-opened.
