### ISSUE TITLE
Change properties of empty revisions

### ISSUE THREAD

**Issue by justinmassiot** [jasperlee108/svndumpfilterIN#12]
The original svndumpfilter tool, when not dropping revisions, automatically erases the author of each empty revision and replaces the log message by "This is an empty revision for padding."
This would be ideal to get a similar behavior with svndumpfilterIN. I even say it would be perfect if the user could pass its own replacement log message as an argument!

**Comment by freeamac** [comment]
Fixed in https://github.com/jasperlee108/svndumpfilterIN/commit/0b24ddf440ce5bdbfd12503d87f372756674d172
