### ISSUE TITLE
Error loading filtered dump

### ISSUE THREAD

**Issue by jehy** [jasperlee108/svndumpfilterIN#13]
Hello! I dump my repository, then filter us with svndumpfilterIN, and then try to import. Everything but import works fine... On import, I get message:

svnadmin: Copy source checksum mismatch on copy from 'trunk/blablabla.cs'@1156
 to 'trunk/blablabla.cs' in rev based on r1175:
   expected:  b59fea0097a34302c059c18313fa59f1
     actual:  969013da335a02a24fd029e3aa98499a

Unfortunately, I can't provide a dump - it is 2GB size.

Can this error be filter's fault?

**Comment by jehy** [comment]
Fixed with removing md5 checksums:

sed -i '/Text-copy-source-md5/d' your.dmp

However, there can possible be some consequences...

**Comment by freeamac** [comment]
Although I found this issue and have submitted a fix for it in a V3 dump, it may also be applicable to V2 formatted dumps:

      4. Fixed untangle logic to pull the current revision via svnlook,
         not the copied from revision. V3 records may include a copy
         from reference and a delta to be applied against that copy.
         If this node is untangled, the delta is not applied (it is
         dropped). If a later revision references this version, it
         pulls the version without the delta applied causing a
         cksum error upon load.
