### ISSUE TITLE
Support for SVN dump version 3

### ISSUE THREAD

**Issue by anessi** [jasperlee108/svndumpfilterIN#15]
Do you plan to add support for SVN-fs-dump-format-version: 3 ? Currently only version 2 is supported and recent svnadmin dump calls produce version 3.

**Comment by freeamac** [comment]
I would like to handle V3. First I need to get a V3 dump.

**Comment by anessi** [comment]
It should be possible to dump some SVN repository using [svnrdump](http://svnbook.red-bean.com/en/1.7/svn.ref.svnrdump.c.dump.html). You can use any public repository to which you have access to all paths (e.g. http://svn.apache.org/repos/asf/subversion/trunk :smiley:

**Comment by anessi** [comment]
sorry, didn't meant to close it

**Comment by freeamac** [comment]
Finally got a dump  I can use. Previous ones took too long to get to revisions which still had accessible source in the repo (ie. subversion fell under this category). Some what smallish repo at 82k revs but something I can start on.
