### ISSUE TITLE
SyntaxError: invalid syntax on first load

### ISSUE THREAD

**Issue by NotoriousBig** [jasperlee108/svndumpfilterIN#29]
Hello, 

I was trying to use the dumpfilter tool to avoid "invalid-copy-source-path-error" but I have an issue while launching the script :

```
[root@SVN ~]$ /EXTRACT/svndumpfilter.py
  File "/EXTRACT/svndumpfilter.py", line 462
    with TemporaryFile() as stdout_temp_file, TemporaryFile() as stderr_temp_file:
                                            ^
SyntaxError: invalid syntax
[root@SVN ~]$
[root@SVN ~]$ nosetests --version
nosetests version 1.3.7
[root@SVN ~]$ python --version
Python 2.6.6
[root@SVN ~]$
```

Do i do something wrong ?

Séb

**Comment by freeamac** [comment]
I just sent a pull request which mentions (in the patch section) that you need to be running on python 2.7.

**Comment by NotoriousBig** [comment]
Hello Freeamac,
Many thanks for saving my life. With your help I managed to split my '56000 revision' dump in 15 repos.
Once again, ty !
