### ISSUE TITLE
Got an error on an operation

### ISSUE THREAD

**Issue by Tdue21** [jasperlee108/svndumpfilterIN#31]
I have a rather large and old repository, which I am trying to clean up. I used svnadmin dump to get a dump file that started at r27000 instead of r0. 
This resulted in a ton of warnings about mergeinfo pointing to missing revisions. 

I then attempted to clean this up by running the dump file through this script: 

> svndumpfilter.py C:\Repositories\Dump\Backup_r27000.dump -x -s -r C:\Repositories\Repository 
> -o C:\Repositories\Dump\FilteredBackup_r27000.dump exclude Department DepartmentOrigin

Some 250 lines of "Stripping property svn:mergeinfo" later I got this: 

> Traceback (most recent call last):
>   File "C:\Share\svndumpfilterIN\svndumpfilter.py", line 961, in <module>
>      main()
>   File "C:\Share\svndumpfilterIN\svndumpfilter.py", line 956, in main
>      parse_dump(input_dump, opt.output_dump, matches, include, opt)
>   File "C:\Share\svndumpfilterIN\svndumpfilter.py", line 807, in parse_dump 
>     node_seg.extract_segment(input_file)
>   File "C:\Share\svndumpfilterIN\svndumpfilter.py", line 322, in extract_segment
>     self._extract_body(d_file)
>   File "C:\Share\svndumpfilterIN\svndumpfilter.py", line 314, in _extract_body
>     self.body = d_file.read(int(self.head[TEXT_CONTENT_LEN]))
> MemoryError

Any thoughts on how to fix this?

**Comment by freeamac** [comment]
Thomas, how large is the dump file you are parsing in bytes? Also you are
starting at r27000 and what is the number of the last revision dumped?

I have used the script on dump file with over 100,000 revisions.

**Comment by freeamac** [comment]
Would need some additional information from the dump file being filtered right around the revision where the issue occurs. You have have a very large text content section which is being read in without enough available ram.

One search to locate a large text section in Linux:

```
$ grep -a Text-content-length <dump_file> | sort -nr | head
Text-content-length: 767
Text-content-length: 381
Text-content-length: 15
```

Closing off unless additional information is available
