### ISSUE TITLE
Keep original revision-numbering

### ISSUE THREAD

**Issue by derMOE** [jasperlee108/svndumpfilterIN#33]
Hi,

I tried to do an export like:
`./svndumpfilter.py -s /tmp/dump/repo.dump include FOLDER1 -r /var/svn -o /tmp/dump.dump`

...and want to keep the original revision-numbering with the option **-s** . But it doesn't work

Then I tried the option **-k and -s:**
`./svndumpfilter.py -s -k /tmp/dump/repo.dump include FOLDER1 -r /var/svn -o /tmp/dump.dump`

...now Iam getting the following error when I try to load the dump into the new repo:
```
<<< Neue Transaktion basierend auf Originalrevision 2957 gestartet

------- Übertrage Revision 2957 >>>

<<< Neue Transaktion basierend auf Originalrevision 2958 gestartet
svnadmin: E140001: Daten des Dateiabzugs scheinen fehlerhaft zu sein
```

Any idea?

**Comment by freeamac** [comment]
Would need to see what is included in the original and filtered dump file in the revisions around 2958 to potentially diagnose the issue

**Comment by freeamac** [comment]
I am unable to reproduce with a couple of test dump files. The "-s" keeps the original numbering. Unless I can see the source and resulting filtered dump file around the problematic revision, I don' t think the issue is being incorrect numbering.
