### ISSUE TITLE
KeyError: 'Node-path'

### ISSUE THREAD

**Issue by sword-huang** [jasperlee108/svndumpfilterIN#35]
Whe I use below command to filte my SVN dump file. The SVN dump file is a big file (6XXGB). 

**python svndumpfilter.py /mnt/dump/svn.dump include "XXX" -r /mnt/data/svn -o XXX.dump**

I get below error message:

Adding revision 9993 to the skipped revisions list
---- Working on Input Revision 9994 (Renumber Rev: 2404) ----
Adding revision 9994 to the skipped revisions list
---- Working on Input Revision 9995 (Renumber Rev: 2404) ----
Adding revision 9995 to the skipped revisions list
---- Working on Input Revision 9996 (Renumber Rev: 2404) ----
Adding revision 9996 to the skipped revisions list
---- Working on Input Revision 9997 (Renumber Rev: 2404) ----
---- Working on Input Revision 9998 (Renumber Rev: 2405) ----
Adding revision 9998 to the skipped revisions list
---- Working on Input Revision 9999 (Renumber Rev: 2405) ----
Traceback (most recent call last):
  File "svndumpfilter.py", line 961, in <module>
    main()
  File "svndumpfilter.py", line 956, in main
    parse_dump(input_dump, opt.output_dump, matches, include, opt)
  File "svndumpfilter.py", line 813, in parse_dump
    if check.is_included(node_seg.head[NODE_PATH]):
KeyError: 'Node-path'

**Comment by freeamac** [comment]
Would need to see the information in revisions 9998 - 10000 in the source dump file to have a chance at debugging. 

The traceback is saying a Node Record is being parsed and one of the required fields in a Node Record is "Node-path" which seems to be missing.

Will close off unless new info is available
